### ISSUE TITLE
What control matrices are usable with BaRatinBAC model ?

### ISSUE THREAD

**Issue by benRenard** [BaM-tools/BaM#11]
In BaRatinBAC, the continuity condition when control $j$ replaces control $j-1$ is written as:

$a_j(\kappa_j-b_j)^{c_j}=a_{j-1}(\kappa_j-b_{j-1})^{c_{j-1}}$

Solving this (no explicit solution => Newton-Raphson) allows computing the activation stage $\kappa_j$ for given values of $a$'s, $b$'s and $c$'s.

There are two problems in the current implementation of BaRatinBAC:

1. line 303 identifies that control $j$ is an addition to the previous control by testing: `if( sum(ControlMatrix(j,:)) > 1 )`. This is not correct: this indeed tests if control $j$ is added to another control, but not necessarily to _the previous one_. Consider for instance: (control1+control3) replaces (control1+control2).
2. It appears that this continuity equation is quite restrictive and does not accommodate many control matrices that are allowed in the original BaRatin k-a-c parameterization. For instance, if control3 replaces (control1+control2), the continuity equation should be:
$a_3(\kappa_3-b_3)^{c_3}=a_{1}(\kappa_3-b_{1})^{c_{1}}+a_{2}(\kappa_3-b_{2})^{c_{2}}$

Given that the existence and uniqueness of solutions  to the continuity equation is tricky, the pragmatic solution at least as a first step would be to identify the class of control matrices allowed in BaRatinBAC, and to return an error message if the specified matrix does not belong to this class. I think the rule may be the following: once you started adding 2 controls, you can only keep adding some more (i.e. no replacement or deletion allowed after the first addition).

@JeromeLeCoz, @Felipemendezrios, what do you think?

**Comment by JeromeLeCoz** [comment]
I think that the rule you propose will accommodate many realistic situations. With this rule, are the existence and uniqueness of solutions to the continuity equation ensured?

**Comment by benRenard** [comment]
Existence and uniqueness are not ensured, but at least we know what to do since this corresponds to the situation described in [Manasanarez et al.](https://doi.org/10.1029/2018WR023389)

**Comment by Felipemendezrios** [comment]
As you mentioned, this could be the initial solution for implementing this rule. However, it is a common scenario for a spillway to function as a means of evacuating excess floodwaters.

**Comment by benRenard** [comment]
> However, it is a common scenario for a spillway to function as a means of evacuating excess floodwaters.

Yes but this will still be manageable through the config: channel then channel + spillway. Similarly channel then channel + spillway1 then channel + spillway1 + spillway2 is still OK because you just keep adding new controls, without replacement. What won't be accepted is (for instance) channel then channel + spillway1 then channel + spillway2 or channel then channel + spillway1 then any other new control.

**Comment by benRenard** [comment]
fixed in commit 9d158c9faa1dee3297f21ec36bfacd2686dd0bab

In fact what I wrote previously was incorrect:  channel + spillway1 then channel + spillway2 is a valid configuration, because the a(h-b)^c of the channel cancels out, leading to the standard continuity equation. 

Changes: 
1. Fixed the incorrect identification of the "control addition" case (see [here](https://github.com/BaM-tools/BaM/blob/9d158c9faa1dee3297f21ec36bfacd2686dd0bab/src/Models/BaRatinBAC_model.f90#L325C1-L325C92))
2. Added more checks when reading the control matrix to try to identify unsupported control matrices as soon as possible. See [these lines](https://github.com/BaM-tools/BaM/blob/9d158c9faa1dee3297f21ec36bfacd2686dd0bab/src/Models/BaRatinBAC_model.f90#L221C1-L252C6).

@Felipemendezrios, @JeromeLeCoz, in case of problem do not hesitate to reopen the ticket.
@IvanHeriver, you may want to use the lines of point 2 if you wish to catch invalid matrices in BaRatinAGE before BaM crashes
