### ISSUE TITLE
Generate prior simulations or prior pdf through the command line

### ISSUE THREAD

**Issue by Felipemendezrios** [BaM-tools/BaM#4]
Save prior distribution realization in a file or a vector to have a record of the values

**Comment by benRenard** [comment]
Could also save the prior pdf, and maybe other useful functions (cdf/quantile?)

Should be done through the command line, e.g. BaM --priorsim outfile.txt

**Comment by benRenard** [comment]
Je ferme en combinant avec le ticket #6
